### ISSUE TITLE
Submit proposal to ActivityPub conference 2020

### ISSUE THREAD

**Issue by acka47** [hbz/skohub.io#13]
See https://conf.activitypub.rocks/. 

**Deadline for proposals is July 8**. As I will be on holidays in July, we would have to submit it next week.

**Comment by acka47** [comment]
@literarymachine Do you have the time and are you interested in co-presenting? As this is pe-recorded we are flexible with regard to the time. Of course, it would be great if you could also attend the q&a.

**Comment by sebilasse** [comment]
Don't spend too much time on this.
A few words about the project and a real brief text summarising the content of your talk is fine.
_Happy Holidays !_

**Comment by acka47** [comment]
@literarymachine and me registered.

@sebilasse As we will present this together both of us added the proposal from http://etherpad.lobid.org/p/apconf2020. 

Closing
