### ISSUE TITLE
Add imprint & contact information

### ISSUE THREAD

**Issue by acka47** [hbz/skohub.io#5]
Link to hbz imprint, add email, Discourse & GitHub issue link for contact.

**Comment by literarymachine** [comment]
> hbz imprint

https://www.hbz-nrw.de/impressum

> add email

which one?

> Discourse

https://socialhub.activitypub.rocks/c/software/skohub

> GitHub issue

https://github.com/hbz/skohub.io/issues

**Comment by acka47** [comment]
Re. email, I'd favour something like `contact@skohub.io` which means to set up an email server. For the start, I could let create `skohub@hbz-nrw.de` but it isn't possible to automatically send mails to this address to @literarymachine ...

**Comment by acka47** [comment]
`skohub@hbz-nrw.de` is set up, so please add it and deploy.
